blank_issues_enabled: false
contact_links:
  - name: Support the project on Ko-fi / Apoya el proyecto en Ko-fi
    url: https://ko-fi.com/A0A618Z66T
    about: Lyricota is free and has no ads. / Lyricota es gratis y sin anuncios.
