apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.example.lrcfetcher'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.lrcfetcher"
        minSdk 26
        targetSdk 34
        versionCode 9
        versionName "2.7"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        compose true
        buildConfig true
    }

    testOptions {
        unitTests.returnDefaultValues = true
        unitTests.includeAndroidResources = true
        unitTests.all {
            jvmArgs '-Dfile.encoding=UTF-8', '-Dsun.stdout.encoding=UTF-8', '-Dsun.stderr.encoding=UTF-8', '--add-opens=java.base/java.io=ALL-UNNAMED'
            systemProperty 'roborazzi.test.record', 'true'
        }
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.5.3'
    }

    packagingOptions {
        resources {
            excludes += [
                'META-INF/CONTRIBUTORS.md',
                'META-INF/LICENSE.md',
                'META-INF/LICENSE',
                'META-INF/LICENSE.txt',
                'META-INF/NOTICE',
                'META-INF/NOTICE.md',
                'META-INF/NOTICE.txt',
                'META-INF/DEPENDENCIES',
                'META-INF/AL2.0',
                'META-INF/LGPL2.1'
            ]
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.activity:activity-compose:1.8.2'
    implementation platform('androidx.compose:compose-bom:2024.02.00')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.7.0'
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'com.atilika.kuromoji:kuromoji-ipadic:0.9.0'
    implementation 'com.ibm.icu:icu4j:75.1'
    debugImplementation 'androidx.compose.ui:ui-tooling'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
    testImplementation 'org.robolectric:robolectric:4.12.2'
    testImplementation 'io.github.takahirom.roborazzi:roborazzi:1.21.0'
    testImplementation 'io.github.takahirom.roborazzi:roborazzi-compose:1.21.0'
    testImplementation 'androidx.compose.ui:ui-test-junit4'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'
}
